version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "${BACKEND_PORT:-3001}:${BACKEND_PORT:-3001}"
    environment:
      - NODE_ENV=production
      - BACKEND_PORT=${BACKEND_PORT:-3001}
      - BACKEND_URL=${BACKEND_URL:-http://localhost:3001}
      - FRONTEND_URL=${FRONTEND_URL:-http://localhost:3000}
    env_file:
      - ./.env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "${FRONTEND_PORT:-3000}:${FRONTEND_PORT:-3000}"
    environment:
      - REACT_APP_BACKEND_URL=${BACKEND_URL:-http://localhost:3001}
    depends_on:
      - backend
